# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Annamaria IEZZI
email: annamaria.iezzi@univ-amu.fr
# description: Page professionnelle d'Annamaria Iezzi, docteur en mathématiques et ATER à Aix-Marseille Université.

 description: Personal homepage of Annamaria Iezzi, Ph.D in Mathematics, currently postdoctoral researcher at University of South Florida.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://annaiezzi.github.io" # the base hostname & protocol for your site

#social:
 # - network: github
  #  username: annaiezzi
  #- network: twitter
  #  username: 13zz1nha
 # - network: facebook
  #  username: annamaria.iezzi
twitter_username: 13zz1nha
github_username:  annaiezzi
facebook_username: annamaria.iezzi
# Build settings
markdown: kramdown
