# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Annamaria IEZZI
email: annamaria.iezzi@univ-amu.fr
description: Site internet d'Annamaria Iezzi.

  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://annaiezzi.github.io" # the base hostname & protocol for your site

#social:
 # - network: github
  #  username: annaiezzi
  #- network: twitter
  #  username: 13zz1nha
 # - network: facebook
  #  username: annamaria.iezzi
twitter_username: 13zz1nha
github_username:  annaiezzi
facebook_usernam: annamaria.iezzi
# Build settings
markdown: kramdown
